/**
 * Even Fibonacci numbers
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
 */

 let evenFibNumberSum = (num) => {
    let arr = Array.from(Array(num + 1), (_, i) => i + 1)

    return arr.reduce((acc, el, i) => {
        if( i > 0) {
            let fibCurrent = el + arr[i - 1]
            if (fibCurrent % 2 === 0) {
                return acc + fibCurrent
            }
        }
    }, 0)
 }