/**
 * Even Fibonacci numbers
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
 */

 let evenFibNumberSum = (num) => {
    let arr = Array.from(Array(num), (_, i) => i + 1)

    let fib = arr.map((el, i) => i > 0 ? el + arr[i-1] : 1)

    return fib.reduce((acc, el) => acc + el, 0)
 }

 console.log(evenFibNumberSum(10))